'use client';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../../lib/supabase';

type Child={id:string;full_name:string;admission_number:string|null;gender:string|null;date_of_birth:string|null;admission_date:string|null;photo_url:string|null;status:string|null;nationality:string|null;religion:string|null;address:string|null;county:string|null;blood_group:string|null;allergies:string|null;medical_conditions:string|null;disability_special_needs:string|null;medication_notes:string|null;emergency_contact_name:string|null;emergency_contact_phone:string|null;emergency_contact_relationship:string|null;previous_school:string|null;birth_certificate_no:string|null;portal_code:string|null;class_name:string|null;stream_name:string|null};
type Dashboard={parent:any;children:Child[];fees:any[];payments:any[];results:any[];attendance:any[];timetable:any[];announcements:any[];transport:any[]};

const money=(n:number)=>new Intl.NumberFormat('en-KE',{style:'currency',currency:'KES',maximumFractionDigits:2}).format(Number(n||0));
export default function ParentPortal(){
 const[data,setData]=useState<Dashboard|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[tab,setTab]=useState('overview');const[childId,setChildId]=useState('');
 useEffect(()=>{(async()=>{const token=sessionStorage.getItem('aic_parent_portal_token');if(!token){location.href='/parent-login';return}if(!supabase){setError('Parent portal is not configured.');setLoading(false);return}const r=await supabase.rpc('parent_portal_dashboard',{p_token:token});if(r.error||!r.data){sessionStorage.removeItem('aic_parent_portal_token');setError('Your portal session has expired. Please log in again.');setLoading(false);return}setData(r.data);setChildId(r.data.children?.[0]?.id||'');setLoading(false)})()},[]);
 const child=data?.children.find(c=>c.id===childId)||data?.children[0];
 const fees=(data?.fees||[]).filter(x=>x.student_id===child?.id);const payments=(data?.payments||[]).filter(x=>x.student_id===child?.id);const results=(data?.results||[]).filter(x=>x.student_id===child?.id);const attendance=(data?.attendance||[]).filter(x=>x.student_id===child?.id);const timetable=(data?.timetable||[]).filter(x=>x.class_id===child?.class_id&&(x.stream_id==null||x.stream_id===child?.stream_id));const transport=(data?.transport||[]).filter(x=>x.student_id===child?.id);
 const due=fees.reduce((a,x)=>a+Number(x.amount_due||0),0),paid=fees.reduce((a,x)=>a+Number(x.amount_paid||0),0),balance=due-paid;
 const groups=useMemo(()=>Object.entries(results.reduce((a:any,r:any)=>{(a[r.exam_name||'Results']??=[]).push(r);return a},{})),[results]);
 function signOut(){sessionStorage.removeItem('aic_parent_portal_token');location.href='/parent-login'}
 if(loading)return <main className="placeholder"><div className="box"><div className="eyebrow">PARENT PORTAL</div><h1>Loading your account…</h1><p>Securely retrieving your child's school records.</p></div></main>;
 if(error)return <main className="placeholder"><div className="box"><div className="eyebrow">PARENT PORTAL</div><h1>Unable to open portal</h1><div className="error">{error}</div><Link href="/parent-login" className="portal-submit">LOGIN AGAIN</Link></div></main>;
 if(!data||!child)return <main className="placeholder"><div className="box"><h1>No linked learner found</h1></div></main>;
 return <main className="portal-dashboard">
  <header className="portal-header"><Link href="/"><Image src="/aic-cathedral-logo.svg" width={62} height={62} alt="AIC Cathedral logo"/></Link><div><div className="eyebrow">AIC CATHEDRAL • PARENT PORTAL</div><h1>Welcome{data.parent?.name?`, ${data.parent.name}`:''}</h1><p className="portal-subtitle">Secure access to your children's school records</p></div><button className="logout" onClick={signOut}>LOG OUT</button></header>
  <nav className="portal-tabs">{[['overview','Overview'],['children','My Children'],['results','Results'],['attendance','Attendance'],['fees','Fees & Payments'],['timetable','Timetable'],['announcements','Announcements']].map(([k,v])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}>{v}</button>)}</nav>
  <section className="portal-wrap">
   {data.children.length>1&&<div className="child-picker"><span>SELECT LEARNER</span><select value={child.id} onChange={e=>setChildId(e.target.value)}>{data.children.map(c=><option key={c.id} value={c.id}>{c.full_name} · {c.admission_number||'No admission number'}</option>)}</select></div>}
   {(tab==='overview'||tab==='children')&&<>
    <div className="portal-hero"><div><span>LEARNER PROFILE</span><h2>{child.full_name}</h2><p>{child.class_name||'Class not assigned'}{child.stream_name?` · ${child.stream_name}`:''} · Admission {child.admission_number||'—'}</p></div><div className="hero-code">SPECIAL CODE<strong>{child.portal_code||'—'}</strong></div></div>
    <div className="portal-stat-grid"><article><span>FEES BALANCE</span><strong>{money(balance)}</strong><small>{money(paid)} paid of {money(due)}</small></article><article><span>ATTENDANCE RECORDS</span><strong>{attendance.length}</strong><small>Recorded school attendance</small></article><article><span>RESULTS</span><strong>{results.length}</strong><small>Published mark records</small></article><article><span>PORTAL STATUS</span><strong>✓ Connected</strong><small>Live school records</small></article></div>
    <div className="portal-two"><section className="portal-panel"><div className="panel-head"><div><span>CHILD INFORMATION</span><h3>Student Details</h3></div></div><div className="detail-grid">{[['Gender',child.gender],['Date of Birth',child.date_of_birth],['Admission Date',child.admission_date],['Nationality',child.nationality],['Religion',child.religion],['County',child.county],['Address',child.address],['Previous School',child.previous_school],['Blood Group',child.blood_group],['Allergies',child.allergies],['Medical Conditions',child.medical_conditions],['Special Needs',child.disability_special_needs],['Medication Notes',child.medication_notes],['Emergency Contact',child.emergency_contact_name],['Emergency Phone',child.emergency_contact_phone]].map(([k,v])=><div key={k}><span>{k}</span><strong>{v||'Not provided'}</strong></div>)}</div></section><section className="portal-panel"><div className="panel-head"><div><span>RECENT PAYMENTS</span><h3>Fee History</h3></div><button onClick={()=>setTab('fees')}>View all</button></div>{payments.slice(0,5).map((p:any)=><div className="list-row" key={p.id}><div><strong>{money(p.amount)}</strong><small>{p.payment_method||'Payment'} · {p.reference_no||'No reference'}</small></div><span>{p.paid_at?new Date(p.paid_at).toLocaleDateString():''}</span></div>)}{!payments.length&&<p className="empty">No payments recorded yet.</p>}</section></div>
   </>}
   {tab==='results'&&<section className="portal-panel"><div className="panel-head"><div><span>ACADEMIC PERFORMANCE</span><h3>Results & Report Marks</h3></div></div>{groups.length?groups.map(([exam,items]:any)=><div className="result-group" key={exam as string}><h4>{exam as string}</h4><div className="result-table">{(items as any[]).map(r=><div className="result-row" key={r.id}><span>{r.learning_area||'Learning Area'}</span><strong>{r.marks??'—'} / {r.max_marks??'—'}</strong><span>{r.achievement_level||'—'}</span><small>{r.remarks||''}</small></div>)}</div></div>):<p className="empty">No results have been published for this learner yet.</p>}</section>}
   {tab==='attendance'&&<section className="portal-panel"><div className="panel-head"><div><span>DAILY RECORD</span><h3>Attendance</h3></div></div>{attendance.length?<div className="result-table">{attendance.map((a:any)=><div className="result-row" key={a.id}><span>{new Date(a.attendance_date).toLocaleDateString()}</span><strong>{a.status}</strong><small>{a.note||''}</small></div>)}</div>:<p className="empty">No attendance records have been entered yet.</p>}</section>}
   {tab==='fees'&&<div className="portal-two"><section className="portal-panel"><div className="panel-head"><div><span>ACCOUNT SUMMARY</span><h3>School Fees</h3></div></div><div className="fee-summary"><div><span>Total Due</span><strong>{money(due)}</strong></div><div><span>Total Paid</span><strong>{money(paid)}</strong></div><div><span>Balance</span><strong>{money(balance)}</strong></div></div>{fees.map((f:any)=><div className="list-row" key={`${f.academic_year_id}-${f.term_id}`}><div><strong>{f.status||'Fee account'}</strong><small>Term account</small></div><strong>{money(f.amount_due)} · Paid {money(f.amount_paid)}</strong></div>)}</section><section className="portal-panel"><div className="panel-head"><div><span>TRANSACTIONS</span><h3>Payments</h3></div></div>{payments.map((p:any)=><div className="list-row" key={p.id}><div><strong>{money(p.amount)}</strong><small>{p.payment_method||'Payment'} · {p.reference_no||'—'}</small></div><span>{p.paid_at?new Date(p.paid_at).toLocaleDateString():''}</span></div>)}{!payments.length&&<p className="empty">No payments recorded.</p>}</section></div>}
   {tab==='timetable'&&<section className="portal-panel"><div className="panel-head"><div><span>CLASS SCHEDULE</span><h3>Timetable</h3></div></div>{timetable.length?<div className="result-table">{timetable.map((t:any)=><div className="result-row" key={t.id}><strong>{t.day}</strong><span>{t.period}</span><span>{t.learning_area||'Learning Area'}</span></div>)}</div>:<p className="empty">No timetable has been published for this learner's class yet.</p>}</section>}
   {tab==='announcements'&&<section className="portal-panel"><div className="panel-head"><div><span>SCHOOL COMMUNICATION</span><h3>Announcements</h3></div></div>{data.announcements.length?data.announcements.map((a:any)=><article className="announcement" key={a.id}><span>{a.created_at?new Date(a.created_at).toLocaleDateString():''}</span><h4>{a.title}</h4><p>{a.body}</p></article>):<p className="empty">No published parent announcements yet.</p>}</section>}
  </section>
  <footer className="portal-footer"><Image src="/aic-cathedral-logo.svg" width={48} height={48} alt="AIC Cathedral logo"/><span>AIC Cathedral Comprehensive School · Parent Portal</span><button onClick={signOut}>Log out</button></footer>
 </main>
}