'use client';
import Image from 'next/image';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { supabase } from '../../lib/supabase';

export default function ParentLogin(){
 const [code,setCode]=useState(''); const [phone,setPhone]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setMessage('');if(!supabase){setMessage('Parent portal is not configured yet. Please contact the school administration.');return}setBusy(true);const {data,error}=await supabase.rpc('parent_portal_create_session',{p_portal_code:code.trim(),p_phone:phone.trim()});setBusy(false);if(error||!data?.[0]?.session_token){setMessage('The Student Special Code and Parent Phone Number could not be verified. Please check them and try again.');return}sessionStorage.setItem('aic_parent_portal_token',data[0].session_token);window.location.href='/parent';}
 return <main className="portal"><div className="portal-card"><Link href="/"><Image className="portal-logo" src="/aic-cathedral-logo.svg" width={90} height={90} alt="AIC Cathedral logo"/></Link><div className="eyebrow">PARENT PORTAL</div><h1>Secure Parent Login</h1><p>Enter your learner's Student Special Code and the phone number registered with the school.</p>{message&&<div className="error">{message}</div>}<form onSubmit={submit}><label className="field"><span>Student Special Code</span><input value={code} onChange={e=>setCode(e.target.value)} placeholder="e.g. AIC-2026-000001" autoComplete="off" required/></label><label className="field"><span>Parent Phone Number</span><input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Phone number registered with school" autoComplete="tel" required/></label><button className="portal-submit" disabled={busy}>{busy?'VERIFYING…':'LOGIN'}</button></form><p className="help">Your credentials are verified securely against the school's records. Need help accessing your account? Contact the school administration.</p><Link href="/" className="forgot">← Return to school website</Link></div></main>}
