'use client';
import Image from 'next/image';
import Link from 'next/link';
import { FormEvent, useState } from 'react';
import { supabase } from '../../lib/supabase';

export default function ParentLogin(){const [username,setUsername]=useState('');const [password,setPassword]=useState('');const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
async function submit(e:FormEvent){e.preventDefault();setMessage('');if(!supabase){setMessage('Parent login is not configured yet. The school administrator needs to add the Supabase environment variables.');return}setBusy(true);const email=username.includes('@')?username.trim():`${username.trim()}@parent.aiccathedral.ac.ke`;const {error}=await supabase.auth.signInWithPassword({email,password});setBusy(false);if(error){setMessage(error.message);return}window.location.href='/parent'}
async function reset(){if(!supabase||!username.includes('@')){setMessage('Enter the email address connected to your parent account, then choose Forgot Password.');return}const {error}=await supabase.auth.resetPasswordForEmail(username.trim(),{redirectTo:`${window.location.origin}/parent-login`});setMessage(error?error.message:'Password reset instructions have been sent if the account exists.');}
return <main className="portal"><div className="portal-card"><Link href="/"><Image className="portal-logo" src="/aic-cathedral-logo.svg" width={90} height={90} alt="AIC Cathedral logo"/></Link><div className="eyebrow">PARENT PORTAL</div><h1>Secure Parent Login</h1><p>Access your secure school account. Parent portal features will be introduced in stages.</p>{message&&<div className={message.toLowerCase().includes('sent')?'success':'error'}>{message}</div>}<form onSubmit={submit}><label className="field"><span>Parent ID / Username</span><input value={username} onChange={e=>setUsername(e.target.value)} placeholder="Parent ID or email" required/></label><label className="field"><span>Password</span><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" required/></label><button className="portal-submit" disabled={busy}>{busy?'LOGGING IN…':'LOGIN'}</button></form><button className="forgot" onClick={reset}>FORGOT PASSWORD?</button><p className="help">Need help accessing your account? Contact the school administration.</p><Link href="/" className="forgot">← Return to school website</Link></div></main>}
