'use client';
import Link from 'next/link';
import { useState } from 'react';

const CLOUDINARY='https://res.cloudinary.com/c4bk5bio/image/upload';
const LOGO=`${CLOUDINARY}/1788855122090.jpg`;
const gallery=[
 [`${CLOUDINARY}/IMG-20260908-WA0015.jpg`,'School Life'],
 [`${CLOUDINARY}/IMG-20260908-WA0016.jpg`,'School Life'],
 [`${CLOUDINARY}/IMG-20260908-WA0017.jpg`,'Learning in Action'],
 [`${CLOUDINARY}/IMG-20260908-WA0018.jpg`,'Student Activities'],
 [`${CLOUDINARY}/IMG-20260908-WA0019.jpg`,'Celebrating Achievement'],
 [`${CLOUDINARY}/IMG-20260908-WA0020.jpg`,'Our Learners']
];
const values=['FAITH','INTEGRITY','EXCELLENCE','DISCIPLINE','RESPECT','RESPONSIBILITY','SERVICE','TEAMWORK'];
const PHONE='0710919020';
const EMAIL='aiccathedraladm@gmail.com';
const PO_BOX='P.O. Box 37, Gilgil – 20116';
export default function Home(){const [open,setOpen]=useState<string|null>(null);return <div>
<div className="top"><div className="container"><span>AIC CATHEDRAL COMPREHENSIVE SCHOOL</span><span>GILGIL · NAKURU COUNTY · KENYA</span><span>Nurturing Excellence, Character & Faith</span></div></div>
<header className="nav"><div className="container navin"><Link href="/" className="brand"><img src={LOGO} width={58} height={58} alt="AIC Cathedral logo" decoding="async"/><span><strong>AIC CATHEDRAL</strong><small>COMPREHENSIVE SCHOOL · GILGIL</small></span></Link><nav className="links"><a href="#about">About Us</a><a href="#academics">Academics</a><a href="#admissions">Admissions</a><a href="#life">School Life</a><a href="#news">News & Events</a><a href="#gallery">Gallery</a><a href="#contact">Contact</a><Link href="/parent-login" className="login">PARENT LOGIN</Link></nav><button className="menu" aria-label="Open menu">☰</button></div></header>
<section className="hero"><div className="container"><div className="eyebrow">WELCOME TO AIC CATHEDRAL</div><h1>Nurturing Excellence, Character & Faith.</h1><p>Welcome to AIC Cathedral Comprehensive School, Gilgil — a Christian learning community dedicated to nurturing learners academically, spiritually, socially and morally.</p><div className="actions"><a className="btn gold" href="#admissions">APPLY FOR ADMISSION</a><Link className="btn light" href="/parent-login">PARENT LOGIN</Link></div></div></section>
<section className="section"><div className="container"><div className="heading"><span>WHY CHOOSE US</span><h2>A place where every learner can grow.</h2></div><div className="why">{[['01','Academic Excellence','Learners are encouraged to develop strong foundations, curiosity and a lifelong love of learning.'],['02','Faith & Character','A Christian environment that encourages integrity, discipline, compassion and responsible living.'],['03','Talent Development','Opportunities to discover gifts, build confidence and grow through creative and co-curricular experiences.'],['04','Caring Community','A welcoming partnership between learners, families and the school community.']].map(x=><article className="card" key={x[0]}><div className="num">{x[0]}</div><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></div></section>
<section id="about" className="section cream"><div className="container split"><div><div className="heading"><span>ABOUT US</span><h2>Growing the whole child.</h2><p>AIC Cathedral Comprehensive School is a Christian learning institution in Gilgil, Nakuru County, Kenya. We seek to provide quality education while supporting learners' academic, spiritual, social, moral and physical development.</p></div><div className="values">{values.map(v=><div className="value" key={v}>{v}</div>)}</div></div><div className="photo"><img src={gallery[3][0]} width={900} height={700} loading="lazy" decoding="async" alt="AIC Cathedral school life"/></div></div></section>
<section id="academics" className="section"><div className="container"><div className="heading"><span>ACADEMICS</span><h2>Learning with purpose.</h2><p>Our academic content is designed to remain editable as the school confirms its official curriculum, learning areas and programmes.</p></div><div className="academic-grid">{[['Curriculum','A learner-centred approach focused on knowledge, skills, values and competencies.'],['Learning Areas','Official learning areas and subject information can be maintained by the school.'],['Assessment','Clear assessment and feedback that supports learner progress.'],['Academic Support','Targeted support that helps learners build confidence and close learning gaps.'],['Digital Learning','Technology-enabled learning resources can be added as the school expands its digital programme.'],['Co-Curricular Learning','Learning beyond the classroom through approved school activities and experiences.']].map(x=><article className="academic" key={x[0]}><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div></div></section>
<section id="life" className="section cream"><div className="container split"><div className="photo"><img src={gallery[0][0]} width={900} height={700} loading="lazy" decoding="async" alt="AIC Cathedral learner activities"/></div><div><div className="heading"><span>SCHOOL LIFE</span><h2>Discover gifts. Build confidence. Serve others.</h2><p>School life can include approved sports, music, drama, clubs, Christian activities, leadership, talent development and community service. Official activities will be updated as the school confirms them.</p></div><div className="values"><div className="value">SPORTS</div><div className="value">MUSIC</div><div className="value">DRAMA</div><div className="value">CLUBS</div><div className="value">CHRISTIAN LIFE</div><div className="value">LEADERSHIP</div></div></div></div></section>
<section className="section"><div className="container"><div className="heading"><span>CHRISTIAN LIFE</span><h2>Growing in faith and character.</h2><p>Prayer, worship, Bible teaching, Christian values, character development, service and fellowship can be represented here using the school's approved content.</p></div></div></section>
<section id="admissions" className="section"><div className="container"><div className="admission"><div><span>ADMISSIONS</span><h2>Begin your child's journey with us.</h2><p>Admission requirements, available classes, fees and important dates will be published here once officially confirmed by the school.</p></div><a className="btn gold" href="#contact">ENQUIRE ABOUT ADMISSION</a></div></div></section>
<section id="news" className="section cream"><div className="container"><div className="heading"><span>NEWS & EVENTS</span><h2>What is happening at school.</h2><p>Academic updates, Christian life, sports, competitions, announcements, school events and community stories will appear here.</p></div><div className="why"><article className="card"><div className="num">NEWS</div><h3>School updates</h3><p>Editable news articles with title, image, date, category, author and content.</p></article><article className="card"><div className="num">EVENTS</div><h3>Upcoming events</h3><p>Event title, date, time, location and description can be maintained by the school.</p></article><article className="card"><div className="num">COMMUNITY</div><h3>Community stories</h3><p>Celebrate approved school milestones and community activities.</p></article></div></div></section>
<section id="gallery" className="section"><div className="container"><div className="heading"><span>GALLERY</span><h2>Life at AIC Cathedral.</h2><p>Real school photographs supplied for the website.</p></div><div className="gallery">{gallery.map(([src,label])=><button key={src} onClick={()=>setOpen(src)}><img src={src} width={800} height={700} loading="lazy" decoding="async" alt={label}/></button>)}</div></div></section>
{open&&<div className="lightbox" onClick={()=>setOpen(null)}><button className="close" onClick={()=>setOpen(null)} aria-label="Close">×</button><img src={open} width={1400} height={1100} decoding="async" alt="AIC Cathedral gallery image"/></div>}
<section id="contact" className="section cream"><div className="container contact"><div className="heading"><span>CONTACT</span><h2>We would love to hear from you.</h2><p>AIC Cathedral Comprehensive School<br/>Gilgil, Nakuru County, Kenya</p></div><div className="contactbox"><p><strong>Phone</strong><br/><a href={`tel:${PHONE}`}>{PHONE}</a></p><p><strong>Email</strong><br/><a href={`mailto:${EMAIL}`}>{EMAIL}</a></p><p><strong>Postal Address</strong><br/>{PO_BOX}</p><p><strong>Office</strong><br/>AIC Cathedral Comprehensive School, Gilgil</p></div></div></section>
<footer><div className="container"><div className="footer-contact"><div><strong>CONTACT US</strong><a href={`tel:${PHONE}`} aria-label="Call AIC Cathedral">☎ <span>{PHONE}</span></a></div><div><strong>EMAIL</strong><a href={`mailto:${EMAIL}`} aria-label="Email AIC Cathedral">✉ <span>{EMAIL}</span></a></div><div><strong>POSTAL ADDRESS</strong><span>⌖ <span>{PO_BOX}</span></span></div></div><div className="footergrid"><div><strong>AIC CATHEDRAL COMPREHENSIVE SCHOOL</strong><p>Nurturing Excellence, Character & Faith</p></div><div><strong>QUICK LINKS</strong><a href="#about">About Us</a><a href="#academics">Academics</a><a href="#admissions">Admissions</a><a href="#gallery">Gallery</a></div><div><strong>PARENT PORTAL</strong><Link href="/parent-login">Parent Login</Link><a href="#contact">Contact School</a></div></div><div className="copy"><span>© 2026 AIC Cathedral Comprehensive School. All Rights Reserved.</span><span>Created by <strong>DIGITAL KINGDOM MEDIA</strong></span></div></div></footer>
</div>}
